const listaAutos = [
    {
        id: "Mitsubishi-L200-4x2", 
        nombre: "Mitsubishi L200 4x2",
        subtitulo: "Pick-up",
        motor: "2.4L Diesel",
        km: "75.000",
        ubicacion: "Arequipa",
        precioContado: "$ 16,500 USD",
        anio: "2019",
        version: "GLS",
        motor: "2.4L Diesel",
        transmision: "Automática",
        otros: "-",
        fotos: ["img/mitsubishil200.jpg","img/L2002.jpg", "img/L2003.jpg", "img/L2004.jpg"] // La primera es la principal
    },
    {
        id: "Kia-Sportage-4x4-2016-mod-2017",
        nombre: "Kia Sportage 4x4 2016 mod 2017",
        subtitulo: "SUV Modelo 2017",
        motor: "2.0L Gasolina",
        km: "53.000",
        ubicacion: "Arequipa",
        precioContado: "S/. 61,000 Soles",
        anio: "2016",
        version: "-",
        transmision: "Mecánica",
        otros: "Parlantes JBL - Tratamiento cerámico",
        fotos: ["img/sportage1.jpg","img/KIASPORTAGE2.jpg", "img/KIASPORTAGE3.jpg", "img/KIASPORTAGE4.jpg", "img/KIASPORTAGE5.jpg", "img/KIASPORTAGE6.jpg", "img/KIASPORTAGE7.jpg", "img/KIASPORTAGE8.jpg"]
    },
    {
        id: "AudiQ5-2012",
        nombre: "Audi Q5 4x4",
        subtitulo: "SUV",
        km: "99,000",
        ubicacion: "Arequipa",
        precioContado: "$ 55,000 USD",
        anio: "2012",
        motor: "2.0L Turbo",
        version: "Quattro",
        transmision: "Automática",
        otros:"Lunas Polarizadas 3M - 8 airbag - Dos llaves",
        fotos: ["img/audiq5.jpg", "img/AUDIQ5-2.png"]
    },
    {
        id: "hyundai-tucson-2019",
        nombre: "Hyundai Tucson",
        subtitulo: "SUV",
        km: "64,000",
        ubicacion: "Arequipa",
        precioContado: "S/. 70,000 PEN",
        anio: "2019",
        motor: "2.0 Gasolina",
        version: "GL",
        transmision: "Mecánica",
        otros:"-",
        fotos: ["img/TUCSON2019.jpg","img/TUCSON2019-2.jpg","img/TUCSON2019-3.jpg","img/TUCSON2019-4.jpg"]
    },
    {
        id: "GLORY-NEW-580",
        nombre: "DFSK GLORY NEW 580",
        subtitulo: "SUV",
        km: "57,000",
        ubicacion: "Arequipa",
        precioContado: "S/. 47,000 PEN",
        anio: "2024",
        motor: "1.8 Bi-Combustible",
        version: "-",
        transmision: "Mecánica",
        otros:"-",
        fotos: ["img/pruebanewglory.png","img/GLORYNEW580-2.png","img/GLORYNEW580-3.png","img/GLORYNEW580-4.png","img/GLORYNEW580-5.png","img/GLORYNEW580-6.png","img/GLORYNEW580-7.png"]
    },
    {
        id: "CHEVROLET-TRACKET-2022",
        nombre: "CHEVROLET TRACKER LTZ",
        subtitulo: "SUV",
        km: "17,000",
        ubicacion: "Arequipa",
        precioContado: "$ 14,500 USD",
        anio: "2022",
        motor: "1.2 Turbo",
        version: "LTZ",
        transmision: "Automática",
        otros:"Pantalla de 8' - AppleCarPlay - Rines de Aleacion 17' - 6 airbags",
        fotos: ["img/HYUNDAITRACKER-1.png","img/HYUNDAITRACKER-2.png","img/HYUNDAITRACKER-3.png","img/HYUNDAITRACKER-4.png","img/HYUNDAITRACKER-5.png","img/HYUNDAITRACKER-6.png"]
    },
    {
        id: "FORLAND-300",
        nombre: "Forland F300 3tn",
        subtitulo: "CAMIÓN",
        km: "1279",
        ubicacion: "AREQUIPA",
        precioContado: "$ 17,000 USD",
        anio: "2024",
        motor: "2.8 Diesel",
        version: "Carga",
        transmision: "Mecánica",
        otros:"-",
        fotos: ["img/FORLANDF300-1.png","img/FORLANDF300-2.png","img/FORLANDF300-4.png"]
    },
    {
        id: "GLORY-580",
        nombre: "DFSK Glory 580",
        subtitulo: "SUV",
        km: "50,000",
        ubicacion: "AREQUIPA",
        precioContado: "S/. 52,000 PEN",
        anio: "2024",
        motor: "1.8 Gasolina",
        version: "-",
        transmision: "-",
        otros:"3 filas asientos - Aros Magnesio 17' - Espejos abatibles - Control de estabilidad - Asientos Ecocuero",
        fotos: ["img/GLORY580-1.png","img/GLORY580-2.png","img/GLORY580-3.png","img/GLORY580-4.png","img/GLORY580-5.png","img/GLORY580-6.png","img/GLORY580-7.png","img/GLORY580-8.png"]
    },
    {
        id: "CHEVROLET-SPIN-2023",
        nombre: "Chevrolet Spin ",
        subtitulo: "MINIVAN",
        km: "20,000",
        ubicacion: "Arequipa",
        precioContado: "S/. 55,000 PEN",
        anio: "2023",
        motor: "1.8 Gasolina/GLP",
        version: "-",
        transmision: "-",
        otros:"7 asientos - 3 filas",
        fotos: ["img/chevSPIN.jpg","img/chevSPIN-2.jpg","img/chevSPIN-3.png","img/chevSPIN-4.jpg","img/chevSPIN-5.png"]
    }, 
    {  
        id: "VOLKSWAGEN-TIGUAN-2012",
        nombre: "Volkswagen Tiguan",
        subtitulo: "-",
        km: "121,000",
        ubicacion: "Juliaca",
        precioContado: "$ 14,700 USD",
        anio: "2012 mod 2013",
        motor: "2.0 Gasolina",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/W-TIGUAN1.png","img/W-TIGUAN2.png"]
    },
    {
        id: "MITSUBISHI-L200-2013",
        nombre: "Mitsubishi L200",
        subtitulo: "PICK-UP",
        km: "105,000",
        ubicacion: "Juliaca",
        precioContado: "S/. 49,500 PEN",
        anio: "2013",
        motor: "-",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/L200-1-2013.png","img/L200-2-2013.png"]
    },
    {
        id: "MITSUBISHI-L200-2025",
        nombre: "Mitsubishi L200",
        subtitulo: "PICK-UP",
        km: "13,000",
        ubicacion: "Juliaca",
        precioContado: "$ 35,000 USD",
        anio: "2025",
        motor: "2.4 Diesel",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/MITSU-L200-1.png","img/MITSU-L200-2.png","img/MITSU-L200-3.png"]
    }, 
    {
        id: "TOYOTA-HILUX-2019",
        nombre: "Toyota Hilux SRV",
        subtitulo: "PICK-UP",
        km: "97,000",
        ubicacion: "Juliaca",
        precioContado: "$ 31,000 USD",
        anio: "2019",
        motor: "-",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/HILUX-2019-1.png","img/HILUX-2019-2.png","img/HILUX-2019-3.png"]
    }, 
    {
        id: "TOYOTA-HILUX-2015",
        nombre: "Toyota Hilux",
        subtitulo: "PICK-UP",
        km: "193,000",
        ubicacion: "Juliaca",
        precioContado: "S/.25,5000 PEN",
        anio: "2015",
        motor: "1kd 3.0",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/TOYOTA-HILUX-2015.png","img/TOYOTA-HILUX-2015-2.png"]
    }, 
    {
        id: "RENAULT-LOGAN-2018",
        nombre: "Renault Logan",
        subtitulo: "Sedán",
        km: "58,800",
        ubicacion: "Juliaca",
        precioContado: "S/.29,500 PEN",
        anio: "2018 Mod 2019",
        motor: "1.6",
        version: "-",
        transmision: "-",
        otros:"Cámara de retroceso - 2 Llaves Originales",
        fotos: ["img/RENAULT-LOGAN-1.png","img/RENAULT-LOGAN-2.png","img/RENAULT-LOGAN-3.png","img/RENAULT-LOGAN-4.png"]
    }, 
    {
        id: "MAZDA-CX5-2016",
        nombre: "Mazda CX-5",
        subtitulo: "SUV",
        km: "--",
        ubicacion: "Juliaca",
        precioContado: "S/. 55,000 PEN",
        anio: "2016 Mod 2017",
        motor: "2.0",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/MAZDA-CX5-1.png","img/MAZDA-CX5-2.png","img/MAZDA-CX5-3.png"]
    }, 
    {
        id: "KING-LONG-2024",
        nombre: "King Long Santana",
        subtitulo: "-",
        km: "21,000",
        ubicacion: "Juliaca",
        precioContado: "S/. 63,000 PEN",
        anio: "2024 Mod 2025",
        motor: "2.7 Diesel T",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/KINGLONG-1.png","img/KINGLONG-2.png","img/KINGLONG-3.png"]
    }, 
    {
        id: "KIA-SOLUTO-SEMIFULL-2021",
        nombre: "Kia Soluto ",
        subtitulo: "Sedán",
        km: "84,114",
        ubicacion: "Juliaca",
        precioContado: "S/.37,000 PEN",
        anio: "2021-2022",
        motor: "1.4 cc",
        version: "Semifull",
        transmision: "Mecánica",
        otros:"Piso tapizado, asientos enmicados, techo enmicado",
        fotos: ["img/KIA-SOLUTO-1.png","img/KIA-SOLUTO-2.png","img/KIA-SOLUTO-3.png","img/KIA-SOLUTO-4.png","img/KIA-SOLUTO-5.png","img/KIA-SOLUTO-6.png","img/KIA-SOLUTO-7.png","img/KIA-SOLUTO-8.png","img/KIA-SOLUTO-9.png"]
    }, 
    {
        id: "HYUNDAI-VERNA-2020",
        nombre: "Hyundai Verna",
        subtitulo: "Sedán",
        km: "75,000",
        ubicacion: "Moquegua",
        precioContado: "S/. 35,000 PEN",
        anio: "2020",
        motor: "-",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/HYUNDAI-VERNA-1.png","img/HYUNDAI-VERNA-2.png","img/HYUNDAI-VERNA-3.png","img/HYUNDAI-VERNA-4.png","img/HYUNDAI-VERNA-5.png","img/HYUNDAI-VERNA-6.png"]
    },   
    {
        id: "JMC-VIGUS-2024",
        nombre: "JMC Vigus Plus",
        subtitulo: "PICK-UP",
        km: "23,000",
        ubicacion: "Tacna",
        precioContado: "S/. 63,000 PEN",
        anio: "2024",
        motor: "2.4 Turbo",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/JMCVIGUS.png","img/JMC-VIGUS-2.png","img/JMC-VIGUS-3.png","img/JMC-VIGUS-4.png"]
    }, 
    {
        id: "TOYOTA-HILUX-2017",
        nombre: "Toyota Hilux SR",
        subtitulo: "PICK-UP",
        km: "93,000",
        ubicacion: "Juliaca",
        precioContado: "$ 21,000 USD",
        anio: "2017",
        motor: "1.0 GD Turbo Intercooler",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/HILUX2017-1.jpg","img/HILUX2017-2.jpg","img/HILUX2017-3.jpg","img/HILUX-2017-4.jpg"]
    }, 
    {
        id: "TOYOTA-RAV4",
        nombre: "Toyota Rav4 Full",
        subtitulo: "SUV",
        km: "152,000",
        ubicacion: "Juliaca",
        precioContado: "S/. 50,000 PEN",
        anio: "2013",
        motor: "2.5cc",
        version: "Full",
        transmision: "-",
        otros:"-",
        fotos: ["img/RAV4-1.jpg","img/RAV4-2.jpg","img/RAV4-3.jpg","img/RAV4-4.jpg"]
    }, 
    {
        id: "NISSAN-NAVARA",
        nombre: "Nissan Navara ",
        subtitulo: "PICK-UP",
        km: "226,000",
        ubicacion: "Juliaca",
        precioContado: "S/. 37,000 PEN",
        anio: "2011",
        motor: "2.5 Turbo Intercooler",
        version: "-",
        transmision: "-",
        otros:"-",
        fotos: ["img/NAVARA1.jpg","img/NAVARA2.jpg","img/NAVARA3.jpg","img/NAVARA4.jpg","img/NAVARA5.jpg","img/NAVARA6.jpg","img/NAVARA7.jpg","img/NAVARA8.jpg","img/NAVARA9.jpg"]
    }, 
    {
        id: "HONDA-HR-V-2022",
        nombre: "Honda HR-V EXL",
        subtitulo: "SUV",
        km: "76,000",
        ubicacion: "Juliaca",
        precioContado: "$ 17,500 USD",
        anio: "2022",
        motor: "1.8cc",
        version: "-",
        transmision: "Mecánica",
        otros:"Paddle shirft - 6 Airbags - Controls estabilidad - Asis.Frenado - Asis. De Pendiente",
        fotos: ["img/HONDA-HR-V.jpg","img/HONDA-HR-V2.jpg","img/HONDA-HR-V3.jpg","img/HONDA-HR-V4.jpg","img/HONDA-HR-V5.jpg","img/HONDA-HR-V6.jpg","img/HONDA-HR-V7.jpg"]
    }, 
    // Agrega aquí los otros 18 siguiendo el mismo formato...
];